[build]
  publish = "docs.source/public"
  command = "git submodule update -f --init && cd docs.source && npm install autoprefixer postcss postcss-cli && hugo --minify"

[build.environment]
  HUGO_VERSION = "0.75.1"
